### DISCUSSION TITLE
how to handle double type with number keyboard?

### DISCUSSION THREAD

**Discussion by mohit-2003** [bosskmk/pluto_grid#564] [Q&A]
How to handle double type with number keyboard?

**Comment by bosskmk** [comment]
Would you like to try modifying the `pubspec.yaml` file as shown below? Please let me know if the issue is resolved and I will proceed with the update.

```yaml
dependencies:
  pluto_grid:
    git:
      url: https://github.com/bosskmk/pluto_grid.git
      ref: feature/keyboard
```

**Reply by mohit-2003** [reply]
**No, it is not working.**
### What did i do ? 

1. Added in pubspec.yaml
```
pluto_grid:
    git:
      url: https://github.com/bosskmk/pluto_grid.git
      ref: feature/keyboard
```

2. Used number() in that column
```
  PlutoColumn(
          title: 'Obtain marks',
          field: 'obtain_marks',
          type: PlutoColumnType.number()),
```

3. Passes double value in every row
```
new PlutoRow(
      cells: {
      'field': PlutoCell(value: 2.5)
      },
    );
```
 
Now in table it becomes **3**, and keyboard is **number** type
