### ISSUE TITLE
[Bug] Tab position precision in column menu.

### ISSUE THREAD

**Issue by MRKDaGods** [bosskmk/pluto_grid#518]
### Steps to reproduce the bug
1- Click the context menu icon of any column.

### Expected results
The context menu is displayed

### Actual results
The column gets resized instead

### Code sample
```dart
Any example of plutogrid
```

### Execution Environment
**Flutter version**
Flutter version is 3.0.4

**PlutoGrid version**
PlutoGrid version is 5.0.4

**OS**
Windows 11

On high dpi devices (ex: Samsung Galaxy Note 20 Ultra) clicking the context menu icon resizes the column instead, due to _isPointMoving being set to true. A simple fix is to add a check for small delta values of moving the mouse as an initial threshold to be passed as shown in the image below.
![image](https://user-images.githubusercontent.com/25166537/179987030-72392c78-af04-42fc-ae7a-0fad9c71c190.png)

**Comment by bosskmk** [comment]
Thanks for the bug report.
I'm going to test it on an HDPI mobile device.

**Comment by bosskmk** [comment]
@MRKDaGods 

Created a branch to test the column menu tab.
Can you test after modifying the pubspec.yaml file as shown below?

```yaml
dependencies:
  pluto_grid:
    git:
      url: https://github.com/bosskmk/pluto_grid.git
      ref: feature/tap_column_menu
```
